service: aws-node-rest-api-typescript

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2
  memorySize: 512

plugins:
  - serverless-offline
functions:
  app:
    handler: src/app.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}